### ISSUE TITLE
SQL error - mysql/mariadb (LMTP/IMAP)

### ISSUE THREAD

**Issue by bajizs** [dbmail/dbmail#200]
Error:[message] _header_value_get_id(+1568): SQLException: Incorrect string value: '\xF0\x9F\x8C\x8D' for column `dbmail`.`dbmail_headervalue`.`sortfield` at row 1

Database Server version: 10.5.16-MariaDB MariaDB package

Here is the actual schema for table.

CREATE TABLE `dbmail_headervalue` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `hash` varchar(255) NOT NULL,
  `headervalue` mediumtext NOT NULL,
  `sortfield` varchar(255) DEFAULT NULL,
  `datefield` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `hash` (`hash`),
  KEY `headervalue` (`headervalue`(255)),
  KEY `sortfield` (`sortfield`),
  KEY `datefield` (`datefield`)
) ENGINE=InnoDB AUTO_INCREMENT=12864581 DEFAULT CHARSET=utf8mb4

**Comment by alan-hicks** [comment]
There is an upgrade script that will change utf8mb3 to utf8mb4 that should fix this issue.
https://github.com/dbmail/dbmail/blob/master/sql/mysql/upgrades/upgrade.mysql

BEGIN;
ALTER DATABASE `dbmail` CHARACTER SET 'utf8mb4';
ALTER TABLE `dbmail_acl` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_aliases` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_authlog` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_auto_notifications` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_auto_replies` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_envelope` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_filters` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_header` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_headername` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_headervalue` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_keywords` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_mailboxes` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_messages` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_mimeparts` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_partlists` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_pbsp` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_physmessage` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_referencesfield` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_replycache` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_sievescripts` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_subscription` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_upgrade_steps` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_usermap` CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE `dbmail_users` CONVERT TO CHARACTER SET utf8mb4;
COMMIT;

**Comment by bajizs** [comment]
No, this script not solve the problem. You can see in first post, actually in database it is done earlier! All datatable is converted to utf8mb4

**Comment by alan-hicks** [comment]
It may be connection or collation, the following query might help:

SHOW VARIABLES
WHERE Variable_name
LIKE 'character\_set\_%'
OR Variable_name
LIKE 'collation%';

The output might look something like the following:

```
+--------------------------+--------------------+
| Variable_name            | Value              |
+--------------------------+--------------------+
| character_set_client     | utf8mb4            |
| character_set_connection | utf8mb4            |
| character_set_database   | utf8mb3            |
| character_set_filesystem | binary             |
| character_set_results    | utf8mb4            |
| character_set_server     | utf8mb4            |
| character_set_system     | utf8mb3            |
| collation_connection     | utf8mb4_0900_ai_ci |
| collation_database       | utf8mb3_general_ci |
| collation_server         | utf8mb4_0900_ai_ci |
+--------------------------+--------------------+
```

Collation is set with dburi in dbmail.conf:

https://www.tildeslash.com/libzdb/#api
https://www.tildeslash.com/libzdb/api-docs/mysqloptions.html

dburi = mysql://localhost:3306/dbmail?user=root&password=swordfish&charset=utf8mb4

**Comment by bajizs** [comment]
Ok.

in dburi was charset=utf8. Now changed to utf8mb4.

I hope it solves the problem.

**Comment by bajizs** [comment]
Hm...

sory to reopen this again, but not solved completely. IMAP and LMTP don't send new error, but dbmail-ustil stil exist....

.Aug 28 02:01:44 mail dbmail-util[20767]: [0x56197f162cc0] Error:[message] dbmail_message_cache_envelope(+1872): SQLException: Incorrect string value: '\xC4NTISB...' for column `dbmail`.`dbmail_envelope`.`envelope` at row 1

Table is created correctly:

CREATE TABLE `dbmail_envelope` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `physmessage_id` bigint(20) unsigned NOT NULL DEFAULT 0,
  `envelope` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `physmessage_id_1` (`physmessage_id`),
  UNIQUE KEY `physmessage_id_2` (`physmessage_id`,`id`),
  CONSTRAINT `dbmail_envelope_ibfk_1` FOREIGN KEY (`physmessage_id`) REFERENCES `dbmail_physmessage` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1994509 DEFAULT CHARSET=utf8mb4


The connection string in dbmail.con is:
dburi                = mysql://localhost:3306/dbmail?user=****&password=****&charset=utf8mb4
